# Generated by Django 3.1.5 on 2021-03-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
